name: Build Simba APK
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build with Buildozer
        uses: Niklas-S-Github/buildozer-action@v1
        with:
          buildozer_version: stable
          python_version: 3.11
          command: android debug
